export const orderTag = 'orders'
export const productPath = '/admin/products'
export const categoryTag = 'categoryProducts'
export const wishlistTag = 'wishlist'
export const typeTag = 'typeProducts'
