import type { Metadata } from 'next';
import { Inter, Advent_Pro } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';
import { SidebarContectProvider } from '../providers/SidebarContext';
import Header from '@/components/Header/Header';
import Wrapper from '@/components/Wrapper/Wrapper';
import { Footer } from '@/components/Footer/Footer';
import { Hero } from '@/components/Hero/Hero';
const inter = Advent_Pro({ subsets: ['latin'], variable: '--font-sans' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <SidebarContectProvider>
        <body
          className={cn(
            'min-h-screen bg-background font-sans text-primary antialiased max-lg:flex max-lg:flex-col',
            inter.variable
          )}
        >
          {children}
        </body>
      </SidebarContectProvider>
    </html>
  );
}
