import type { Metadata } from 'next';
import { Inter, Advent_Pro } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';
import { SidebarContectProvider } from '../providers/SidebarContext';

import { SessionProvider, useSession } from 'next-auth/react';
import { auth } from '@/auth';

const inter = Advent_Pro({ subsets: ['latin'], variable: '--font-sans' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <SessionProvider session={session}>
      <html lang='en'>
        <SidebarContectProvider>
          <body
            className={cn(
              'min-h-screen bg-background font-sans text-primary antialiased max-lg:flex max-lg:flex-col',
              inter.variable
            )}
          >
            {children}
          </body>
        </SidebarContectProvider>
      </html>
    </SessionProvider>
  );
}
